# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 64e1d4c7932366fd53f50746e822998c202b18a598567587706f454c65b1f20878ab3bbc1c67f6ce9a7d644d216f68030a0983e8fd5eb8ea65679b8929a87ceb

test:
  domain_name: example.com 
  secret_key_base: 618844ce0262a8cc9e5db2e50a23f5723024bc03701a07670bcc37ca27c270cdabb4e20563cc5c21bd7ec69c6e1f9c8354899c961d7ca54640c57034da22035a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
